---
backend:
  branch: master
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - files:
      - fields:
          - default: index-page
            label: "Template Key"
            name: templateKey
            widget: hidden
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Heading
            name: heading
            widget: string
          - label: Subheading
            name: subheading
            widget: string
          - label: Description
            name: description
            widget: string
        file: src/pages/index.md
        label: "Home Page"
        name: index
    label: Pages
    name: pages
  - create: true
    fields:
      - default: gallery-image
        label: "Template Key"
        name: templateKey
        widget: hidden
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Image
        name: image
        widget: image
    folder: src/pages/gallery
    label: "Gallery Image"
    name: gallery
    slug: "{{slug}}"
